// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: coordinates.sql

package database

import (
	"context"
	"time"
)

const addCoordinates = `-- name: AddCoordinates :one
INSERT INTO geo_data (latitude, longitude, altitude, tmstmp)
VALUES($1, $2, $3, $4)
RETURNING id, latitude, longitude, altitude, tmstmp
`

type AddCoordinatesParams struct {
	Latitude  float64
	Longitude float64
	Altitude  float64
	Tmstmp    time.Time
}

func (q *Queries) AddCoordinates(ctx context.Context, arg AddCoordinatesParams) (GeoDatum, error) {
	row := q.db.QueryRowContext(ctx, addCoordinates,
		arg.Latitude,
		arg.Longitude,
		arg.Altitude,
		arg.Tmstmp,
	)
	var i GeoDatum
	err := row.Scan(
		&i.ID,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Tmstmp,
	)
	return i, err
}
