// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"time"
)

type GeoDatum struct {
	ID        int32
	Latitude  float64
	Longitude float64
	Altitude  float64
	Tmstmp    time.Time
}
